USE LIBRARY_DB 

-- 2.SORU'NUN CEVABI

-- ÜYELER VERÝ EKLEME
INSERT INTO UYELER (UYE_ADI, UYE_SOYADI, CINSIYET, ADRES_NO, TELEFON, E_POSTA)
VALUES ('Ahmet', 'Yýlmaz', 1, 2, '5551234567', 'ahmet@example.com');

--ÜYELER VERÝ GÜNCELEME
UPDATE UYELER
SET UYE_ADI = 'Mehmet', UYE_SOYADI = 'Yýldýz', CINSIYET = 0, ADRES_NO = 3, TELEFON = '5559876543', E_POSTA = 'mehmet@example.com'
WHERE UYE_NO = 1;

-- ÜYELER VERÝ SÝLMEK ÝÇÝN
DELETE FROM UYELER WHERE UYE_NO = 1;

--ADRESLER VERÝ EKLEME 
INSERT INTO ADRESLER (CADDE, MAHALLE, BINA_NO, SEHIR, POSTA_KODU, ULKE)
VALUES ('Mehmet Akif', 'Yeþilyurt', '123', 'Adýyaman', 12345, 'Türkiye');

--ADRESLER VERÝ GÜNCELLEME 
UPDATE ADRESLER
SET CADDE = 'Mevlana', MAHALLE = 'Talas', BINA_NO = '456', SEHIR = 'Kayseri', POSTA_KODU = 54321, ULKE = 'Türkiye'
WHERE ADRES_NO = 1;

--ADRESLER VERÝ SÝLME 
DELETE FROM ADRESLER WHERE ADRES_NO = 1;

--KÜTÜPHANE VERÝ EKLEME 
INSERT INTO KUTUPHANE (ADRES_NO, KUTUPHANE_ADI, ACIKLAMA)
VALUES (1, '7/24', '7/24 açýk kütüphane');


--KÜTÜPHANE VERÝ GÜNCELLEME
UPDATE KUTUPHANE
SET KUTUPHANE_ADI = 'Mevlana', ACIKLAMA = 'Mevlana Mahalesinde 10 Yýldýr Açýk'
WHERE KUTUPHANE_NO = 1;


--KÜTÜPHANE VERÝ SÝLME
DELETE FROM KUTUPHANE WHERE KUTUPHANE_NO = 1;


--EMANET VERÝ EKLEME 
INSERT INTO EMANET (ISBN, UYE_NO, KUTUPHANE_NO, EMANET_TARIHI, TESLIM_TARIHI)
VALUES ('6055937515', 1, 1, '2009-10-12', '2009-10-17');


-- EMANET VERÝ GÜNCELLEME 
UPDATE EMANET
SET TESLIM_TARIHI = '2009-10-18'
WHERE EMANET_NO = 1;


-- EMANET VERÝ SÝLME 
DELETE FROM EMANET WHERE EMANET_NO = 1;


--KÝTAPLAR VERÝ EKLEME 
INSERT INTO KITAPLAR (ISBN, KITAP_ADI, YAYIN_TARIHI, S_SAYISI)
VALUES ('6055937546', 'Veri Tabaný Yönetim Sistemleri', '2009-10-01', 405);

--KÝTAPLAR VERÝ GÜNCELLEME 
UPDATE KITAPLAR
SET S_SAYISI = 320
WHERE ISBN = '6055937515';

--KÝTAPLAR VERÝ SÝLME 
DELETE FROM KITAPLAR WHERE ISBN = '6055937515';

-- YAZARLAR VERÝ EKLEME 
 INSERT INTO YAZARLAR (YAZAR_ADI, YAZAR_SOYADI)
VALUES ('Arif Cahit', 'Zarifoðlu');

 --YAZARLAR VERÝ GÜNCELLEME 
 UPDATE YAZARLAR
SET YAZAR_SOYADI = 'TAÞ'
WHERE YAZAR_NO = 3;

 --YAZARLAR VERÝ SÝLME 
 DELETE FROM YAZARLAR WHERE YAZAR_NO = 1;



 ---KATEGORÝLER VERÝ EKLEME 
 INSERT INTO KATEGORILER (KATEGORI_ADI)
VALUES ('Çocuk Geliþimi');

 --KATEGORÝLER VERÝ GÜNCELLEME 
 UPDATE KATEGORILER
SET KATEGORI_ADI = 'Felsefe'
WHERE KATEGORI_NO = 7;

 --KATEGORÝLER VERÝ SÝLME 
 DELETE FROM KATEGORILER WHERE KATEGORI_NO = 3;


 --KÝTAP_KÜTÜPHANE VERÝ EKLEME 
INSERT INTO KITAP_KUTUPHANE (KUTUPHANE_NO, ISBN, MIKTAR)
VALUES (1, '6055937589', 3); 


 --KÝTAP_KÜTÜPHANE VERÝ GÜNCELLEME 
UPDATE KITAP_KUTUPHANE
SET MIKTAR = 5
WHERE KUTUPHANE_NO = 1 AND ISBN = '6055937515';



 -- KÝTAP_KÜTÜPHANE VERÝ SÝLME 
DELETE FROM KITAP_KUTUPHANE
WHERE KUTUPHANE_NO = 1 AND ISBN = '6055937515';


 --KÝTAP_KATEGORÝ VERÝ EKLEME 
INSERT INTO KITAP_KATEGORI (ISBN, KATEGORI_NO)
VALUES ('6055937535', 1); 

 --KÝTAP_KATEGORÝ VERÝ GÜNCELLEME 
UPDATE KITAP_KATEGORI
SET KATEGORI_NO = 2
WHERE ISBN = '605593882334' AND KATEGORI_NO = 1; 

 --KÝTAP_KATEGORÝ VERÝ SÝLME 
DELETE FROM KITAP_KATEGORI
WHERE ISBN = '6055937515' AND KATEGORI_NO = 1; 



 --KÝTAP_YAZAR VERÝ EKLEME 
INSERT INTO KITAP_YAZAR (ISBN, YAZAR_NO)
VALUES ('6055937515', 1); 

 -- KÝTAP_YAZAR VERÝ GÜNCELLEME

UPDATE KITAP_YAZAR
SET ISBN = '6052937549', YAZAR_NO = 18
WHERE ISBN = '6055937515' AND YAZAR_NO = 1; 

 --KÝTAP_YAZAR VERÝ SÝLME 
DELETE FROM KITAP_YAZAR
WHERE ISBN = '6055937515' AND YAZAR_NO = 2;


--3.SORU'NUN CEVABI
SELECT * FROM UYELER
ORDER BY UYE_NO ASC;

--4.SORU'NUN CEVABI
SELECT * FROM EMANET
WHERE EMANET_TARIHI > '2023-01-31';

--5.SORU'NUN CEVABI
--ÜYELER TABLOSUNDA BULUNAN VERÝLERDE ÞEHÝR BULUNAMAKTADIR O YÜZDEN ÇAÐIRMA ÝÞLEMÝ GERÇEKLEÞMEYECEKTÝR.
SELECT * FROM UYELER
WHERE SEHIR = 'Kayseri' AND TELEFON LIKE '%6%';

--6.SORU'NUN CEVABI
SELECT * FROM EMANET
WHERE DATEDIFF(day, GETDATE(), TESLIM_TARIHI) < 30;

--7.SORU'NUN CEVABI
-- OLUÞTURDUÐUMUZ LIBRARY_DB VERÝTABANINA AÝT BÝR TABLODA ÝSTENÝLEN VERÝLER BULUNMAMKTA O YÜZDEN SORUNUN CEVABINI YAZDIM AMA VERÝTABNINA AÝT DEÐÝLDÝR.
SELECT CONCAT(SUBSTRING(Ad, 1, 1), ' ', LEFT(Soyad, 5)) AS YeniAdSoyad
FROM UYELER
WHERE LEN(Soyad) > 5
ORDER BY YeniAdSoyad;

--8.SORU'NUN CEVABI
--ÜYELER VERÝTABANINA AÝT ÞEHÝR SÜTUN'U BULUNMAMAKTA SADECE SORUNUN CEVABINI YAZDIM.
SELECT Sehir
FROM UYELER
ORDER BY Sehir;

--9.SORU'NUN CEVABI
SELECT COUNT(*)
FROM EMANET
WHERE YEAR(EMANET_TARIHI) = 2020;

--10.SORU'NUN CEVABI
SELECT *
FROM EMANET
WHERE KUTUPHANE_NO IN (SELECT KUTUPHANE_NO FROM KUTUPHANE WHERE KUTUPHANE_ADI = 'Kayseri Belediyesi Merkez Kütüphanesi')
AND DATEDIFF(MONTH, EMANET_TARIHI, TESLIM_TARIHI) > 6;


--11.SORU'NUN CEVABI
--ÜYELER VERÝTABANINA AÝT ÞEHÝR SÜTUN'U BULUNMAMAKTA SADECE SORUNUN CEVABINI YAZDIM.
SELECT COUNT(*) AS Eskiþehirde_Yasayan_Uye_Sayisi
FROM UYELER
WHERE SEHIR = 'Eskiþehir';

--12.SORU'NUN CEVABI
SELECT YAZARLAR.YAZAR_ADI, YAZARLAR.YAZAR_SOYADI
FROM KITAPLAR
JOIN KITAP_YAZAR ON KITAPLAR.ISBN = KITAP_YAZAR.ISBN
JOIN YAZARLAR ON KITAP_YAZAR.YAZAR_NO = YAZARLAR.YAZAR_NO
WHERE DATEDIFF(YEAR, KITAPLAR.YAYIN_TARIHI, GETDATE()) > 3;

--13.SORU'NUN CEVABI
--HER KÝTAP ÝÇÝN EN UZUN SÜREYÝ BULMA
SELECT ISBN, MAX(DATEDIFF(DAY, EMANET_TARIHI, TESLIM_TARIHI)) AS En_Uzun_Sure
FROM EMANET
GROUP BY ISBN;
--HER KÝTAP ÝÇÝN EN KISA SÜREYÝ BULMA
SELECT ISBN, MIN(DATEDIFF(DAY, EMANET_TARIHI, TESLIM_TARIHI)) AS En_Kisa_Sure
FROM EMANET
GROUP BY ISBN;

--14.SORU'NUN CEVABI
SELECT KITAPLAR.ISBN, KITAP_ADI, UYE_ADI, UYE_SOYADI
FROM EMANET
INNER JOIN KITAPLAR ON EMANET.ISBN = KITAPLAR.ISBN
INNER JOIN UYELER ON EMANET.UYE_NO = UYELER.UYE_NO;

